spring.application.name=be_lms
spring.data.mongodb.uri=mongodb+srv://hungson:159357852@lms.dbejaog.mongodb.net/elearning_db?retryWrites=true&w=majority&appName=LMS
vnpay.tmnCode=9VN9YKH4
vnpay.hashSecret=Q6JYZ6JKEKMEHH0B9PMZBSIYU5FQ7G2G
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://localhost:8080/api/vnpay/return